/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface CostSettings {
  'selectionServiceCost' : number,
  'deliveryCost' : number,
  'epTsCost' : number,
}
export interface CurrencyAndCostSettings {
  'selectionServiceCost' : number,
  'euroRate' : number,
  'deliveryCost' : number,
  'yuanRate' : number,
  'epTsCost' : number,
}
export interface CurrencyRates { 'euro' : number, 'yuan' : number }
export type ExternalBlob = Uint8Array;
export interface Review {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'comment' : string,
  'images' : Array<ExternalBlob>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'model' : string,
  'mileage' : bigint,
  'color' : string,
  'trim' : string,
  'year' : bigint,
  'description' : string,
  'brand' : string,
  'engineVolume' : bigint,
  'priceInYuan' : bigint,
  'horsepower' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[Review], bigint>,
  'addVehicle' : ActorMethod<[Vehicle], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactFormSubmission' : ActorMethod<[bigint], boolean>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'deleteVehicle' : ActorMethod<[bigint], boolean>,
  'duplicateVehicle' : ActorMethod<[bigint], [] | [bigint]>,
  'getActiveFilters' : ActorMethod<
    [],
    {
      'brands' : Array<string>,
      'models' : Array<string>,
      'colors' : Array<string>,
    }
  >,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getBrands' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getColors' : ActorMethod<[], Array<string>>,
  'getCostSettings' : ActorMethod<[], CostSettings>,
  'getCurrencyAndCostSettings' : ActorMethod<[], CurrencyAndCostSettings>,
  'getCurrencyRates' : ActorMethod<[], CurrencyRates>,
  'getModelsByBrand' : ActorMethod<[string], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], [] | [Vehicle]>,
  'getVehiclesByFilter' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    Array<Vehicle>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCostSettings' : ActorMethod<[number, number, number], undefined>,
  'setCurrencyAndCostSettings' : ActorMethod<
    [number, number, number, number, number],
    undefined
  >,
  'setCurrencyRates' : ActorMethod<[number, number], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateReview' : ActorMethod<[bigint, Review], boolean>,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];