/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'color' : IDL.Text,
  'trim' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'brand' : IDL.Text,
  'engineVolume' : IDL.Nat,
  'priceInYuan' : IDL.Nat,
  'horsepower' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CostSettings = IDL.Record({
  'selectionServiceCost' : IDL.Float64,
  'deliveryCost' : IDL.Float64,
  'epTsCost' : IDL.Float64,
});
export const CurrencyAndCostSettings = IDL.Record({
  'selectionServiceCost' : IDL.Float64,
  'euroRate' : IDL.Float64,
  'deliveryCost' : IDL.Float64,
  'yuanRate' : IDL.Float64,
  'epTsCost' : IDL.Float64,
});
export const CurrencyRates = IDL.Record({
  'euro' : IDL.Float64,
  'yuan' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([Review], [IDL.Nat], []),
  'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactFormSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'duplicateVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'getActiveFilters' : IDL.Func(
      [],
      [
        IDL.Record({
          'brands' : IDL.Vec(IDL.Text),
          'models' : IDL.Vec(IDL.Text),
          'colors' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getColors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCostSettings' : IDL.Func([], [CostSettings], ['query']),
  'getCurrencyAndCostSettings' : IDL.Func(
      [],
      [CurrencyAndCostSettings],
      ['query'],
    ),
  'getCurrencyRates' : IDL.Func([], [CurrencyRates], ['query']),
  'getModelsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'getVehiclesByFilter' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCostSettings' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Float64], [], []),
  'setCurrencyAndCostSettings' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setCurrencyRates' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateReview' : IDL.Func([IDL.Nat, Review], [IDL.Bool], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'color' : IDL.Text,
    'trim' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'brand' : IDL.Text,
    'engineVolume' : IDL.Nat,
    'priceInYuan' : IDL.Nat,
    'horsepower' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CostSettings = IDL.Record({
    'selectionServiceCost' : IDL.Float64,
    'deliveryCost' : IDL.Float64,
    'epTsCost' : IDL.Float64,
  });
  const CurrencyAndCostSettings = IDL.Record({
    'selectionServiceCost' : IDL.Float64,
    'euroRate' : IDL.Float64,
    'deliveryCost' : IDL.Float64,
    'yuanRate' : IDL.Float64,
    'epTsCost' : IDL.Float64,
  });
  const CurrencyRates = IDL.Record({
    'euro' : IDL.Float64,
    'yuan' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([Review], [IDL.Nat], []),
    'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactFormSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'duplicateVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'getActiveFilters' : IDL.Func(
        [],
        [
          IDL.Record({
            'brands' : IDL.Vec(IDL.Text),
            'models' : IDL.Vec(IDL.Text),
            'colors' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getColors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCostSettings' : IDL.Func([], [CostSettings], ['query']),
    'getCurrencyAndCostSettings' : IDL.Func(
        [],
        [CurrencyAndCostSettings],
        ['query'],
      ),
    'getCurrencyRates' : IDL.Func([], [CurrencyRates], ['query']),
    'getModelsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'getVehiclesByFilter' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCostSettings' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setCurrencyAndCostSettings' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setCurrencyRates' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateReview' : IDL.Func([IDL.Nat, Review], [IDL.Bool], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };